/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CondicionesDeVentaRouteImport } from './routes/condiciones-de-venta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DisenoGraficoRouteImport } from './routes/diseno-grafico'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EventosPersonalizadosRouteImport } from './routes/eventos-personalizados'
import { Route as GranFormatoRouteImport } from './routes/gran-formato'
import { Route as ImprentaRouteImport } from './routes/imprenta'
import { Route as ImpresionTextilRouteImport } from './routes/impresion-textil'
import { Route as InvitacionesDeBodaRouteImport } from './routes/invitaciones-de-boda'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MerchandisingRouteImport } from './routes/merchandising'
import { Route as NaturhouseRouteImport } from './routes/naturhouse'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as RegalosPersonalizadosRouteImport } from './routes/regalos-personalizados'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedCuentaIndexRouteImport } from './routes/_authenticated/cuenta.index'
import { Route as AuthenticatedCuentaDescargasRouteImport } from './routes/_authenticated/cuenta.descargas'
import { Route as AuthenticatedCuentaDetallesRouteImport } from './routes/_authenticated/cuenta.detalles'
import { Route as AuthenticatedCuentaDireccionesRouteImport } from './routes/_authenticated/cuenta.direcciones'
import { Route as AuthenticatedCuentaPedidosRouteImport } from './routes/_authenticated/cuenta.pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicionesDeVentaRoute = CondicionesDeVentaRouteImport.update({
  id: '/condiciones-de-venta',
  path: '/condiciones-de-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoGraficoRoute = DisenoGraficoRouteImport.update({
  id: '/diseno-grafico',
  path: '/diseno-grafico',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosPersonalizadosRoute = EventosPersonalizadosRouteImport.update({
  id: '/eventos-personalizados',
  path: '/eventos-personalizados',
  getParentRoute: () => rootRouteImport,
} as any)
const GranFormatoRoute = GranFormatoRouteImport.update({
  id: '/gran-formato',
  path: '/gran-formato',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprentaRoute = ImprentaRouteImport.update({
  id: '/imprenta',
  path: '/imprenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpresionTextilRoute = ImpresionTextilRouteImport.update({
  id: '/impresion-textil',
  path: '/impresion-textil',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionesDeBodaRoute = InvitacionesDeBodaRouteImport.update({
  id: '/invitaciones-de-boda',
  path: '/invitaciones-de-boda',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandisingRoute = MerchandisingRouteImport.update({
  id: '/merchandising',
  path: '/merchandising',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturhouseRoute = NaturhouseRouteImport.update({
  id: '/naturhouse',
  path: '/naturhouse',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegalosPersonalizadosRoute = RegalosPersonalizadosRouteImport.update({
  id: '/regalos-personalizados',
  path: '/regalos-personalizados',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCuentaIndexRoute =
  AuthenticatedCuentaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCuentaRoute,
  } as any)
const AuthenticatedCuentaDescargasRoute =
  AuthenticatedCuentaDescargasRouteImport.update({
    id: '/descargas',
    path: '/descargas',
    getParentRoute: () => AuthenticatedCuentaRoute,
  } as any)
const AuthenticatedCuentaDetallesRoute =
  AuthenticatedCuentaDetallesRouteImport.update({
    id: '/detalles',
    path: '/detalles',
    getParentRoute: () => AuthenticatedCuentaRoute,
  } as any)
const AuthenticatedCuentaDireccionesRoute =
  AuthenticatedCuentaDireccionesRouteImport.update({
    id: '/direcciones',
    path: '/direcciones',
    getParentRoute: () => AuthenticatedCuentaRoute,
  } as any)
const AuthenticatedCuentaPedidosRoute =
  AuthenticatedCuentaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedCuentaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/condiciones-de-venta': typeof CondicionesDeVentaRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/empresa': typeof EmpresaRoute
  '/eventos-personalizados': typeof EventosPersonalizadosRoute
  '/gran-formato': typeof GranFormatoRoute
  '/imprenta': typeof ImprentaRoute
  '/impresion-textil': typeof ImpresionTextilRoute
  '/invitaciones-de-boda': typeof InvitacionesDeBodaRoute
  '/mcp': typeof McpRoute
  '/merchandising': typeof MerchandisingRoute
  '/naturhouse': typeof NaturhouseRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/regalos-personalizados': typeof RegalosPersonalizadosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cuenta': typeof AuthenticatedCuentaRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cuenta/descargas': typeof AuthenticatedCuentaDescargasRoute
  '/cuenta/detalles': typeof AuthenticatedCuentaDetallesRoute
  '/cuenta/direcciones': typeof AuthenticatedCuentaDireccionesRoute
  '/cuenta/pedidos': typeof AuthenticatedCuentaPedidosRoute
  '/cuenta/': typeof AuthenticatedCuentaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/condiciones-de-venta': typeof CondicionesDeVentaRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/empresa': typeof EmpresaRoute
  '/eventos-personalizados': typeof EventosPersonalizadosRoute
  '/gran-formato': typeof GranFormatoRoute
  '/imprenta': typeof ImprentaRoute
  '/impresion-textil': typeof ImpresionTextilRoute
  '/invitaciones-de-boda': typeof InvitacionesDeBodaRoute
  '/mcp': typeof McpRoute
  '/merchandising': typeof MerchandisingRoute
  '/naturhouse': typeof NaturhouseRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/regalos-personalizados': typeof RegalosPersonalizadosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cuenta/descargas': typeof AuthenticatedCuentaDescargasRoute
  '/cuenta/detalles': typeof AuthenticatedCuentaDetallesRoute
  '/cuenta/direcciones': typeof AuthenticatedCuentaDireccionesRoute
  '/cuenta/pedidos': typeof AuthenticatedCuentaPedidosRoute
  '/cuenta': typeof AuthenticatedCuentaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/condiciones-de-venta': typeof CondicionesDeVentaRoute
  '/contacto': typeof ContactoRoute
  '/diseno-grafico': typeof DisenoGraficoRoute
  '/empresa': typeof EmpresaRoute
  '/eventos-personalizados': typeof EventosPersonalizadosRoute
  '/gran-formato': typeof GranFormatoRoute
  '/imprenta': typeof ImprentaRoute
  '/impresion-textil': typeof ImpresionTextilRoute
  '/invitaciones-de-boda': typeof InvitacionesDeBodaRoute
  '/mcp': typeof McpRoute
  '/merchandising': typeof MerchandisingRoute
  '/naturhouse': typeof NaturhouseRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/regalos-personalizados': typeof RegalosPersonalizadosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/cuenta/descargas': typeof AuthenticatedCuentaDescargasRoute
  '/_authenticated/cuenta/detalles': typeof AuthenticatedCuentaDetallesRoute
  '/_authenticated/cuenta/direcciones': typeof AuthenticatedCuentaDireccionesRoute
  '/_authenticated/cuenta/pedidos': typeof AuthenticatedCuentaPedidosRoute
  '/_authenticated/cuenta/': typeof AuthenticatedCuentaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aviso-legal'
    | '/carrito'
    | '/checkout'
    | '/condiciones-de-venta'
    | '/contacto'
    | '/diseno-grafico'
    | '/empresa'
    | '/eventos-personalizados'
    | '/gran-formato'
    | '/imprenta'
    | '/impresion-textil'
    | '/invitaciones-de-boda'
    | '/mcp'
    | '/merchandising'
    | '/naturhouse'
    | '/politica-de-privacidad'
    | '/regalos-personalizados'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cuenta'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cuenta/descargas'
    | '/cuenta/detalles'
    | '/cuenta/direcciones'
    | '/cuenta/pedidos'
    | '/cuenta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aviso-legal'
    | '/carrito'
    | '/checkout'
    | '/condiciones-de-venta'
    | '/contacto'
    | '/diseno-grafico'
    | '/empresa'
    | '/eventos-personalizados'
    | '/gran-formato'
    | '/imprenta'
    | '/impresion-textil'
    | '/invitaciones-de-boda'
    | '/mcp'
    | '/merchandising'
    | '/naturhouse'
    | '/politica-de-privacidad'
    | '/regalos-personalizados'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cuenta/descargas'
    | '/cuenta/detalles'
    | '/cuenta/direcciones'
    | '/cuenta/pedidos'
    | '/cuenta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/aviso-legal'
    | '/carrito'
    | '/checkout'
    | '/condiciones-de-venta'
    | '/contacto'
    | '/diseno-grafico'
    | '/empresa'
    | '/eventos-personalizados'
    | '/gran-formato'
    | '/imprenta'
    | '/impresion-textil'
    | '/invitaciones-de-boda'
    | '/mcp'
    | '/merchandising'
    | '/naturhouse'
    | '/politica-de-privacidad'
    | '/regalos-personalizados'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/cuenta'
    | '/categoria/$slug'
    | '/producto/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/cuenta/descargas'
    | '/_authenticated/cuenta/detalles'
    | '/_authenticated/cuenta/direcciones'
    | '/_authenticated/cuenta/pedidos'
    | '/_authenticated/cuenta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  CondicionesDeVentaRoute: typeof CondicionesDeVentaRoute
  ContactoRoute: typeof ContactoRoute
  DisenoGraficoRoute: typeof DisenoGraficoRoute
  EmpresaRoute: typeof EmpresaRoute
  EventosPersonalizadosRoute: typeof EventosPersonalizadosRoute
  GranFormatoRoute: typeof GranFormatoRoute
  ImprentaRoute: typeof ImprentaRoute
  ImpresionTextilRoute: typeof ImpresionTextilRoute
  InvitacionesDeBodaRoute: typeof InvitacionesDeBodaRoute
  McpRoute: typeof McpRoute
  MerchandisingRoute: typeof MerchandisingRoute
  NaturhouseRoute: typeof NaturhouseRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  RegalosPersonalizadosRoute: typeof RegalosPersonalizadosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condiciones-de-venta': {
      id: '/condiciones-de-venta'
      path: '/condiciones-de-venta'
      fullPath: '/condiciones-de-venta'
      preLoaderRoute: typeof CondicionesDeVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-grafico': {
      id: '/diseno-grafico'
      path: '/diseno-grafico'
      fullPath: '/diseno-grafico'
      preLoaderRoute: typeof DisenoGraficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos-personalizados': {
      id: '/eventos-personalizados'
      path: '/eventos-personalizados'
      fullPath: '/eventos-personalizados'
      preLoaderRoute: typeof EventosPersonalizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gran-formato': {
      id: '/gran-formato'
      path: '/gran-formato'
      fullPath: '/gran-formato'
      preLoaderRoute: typeof GranFormatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprenta': {
      id: '/imprenta'
      path: '/imprenta'
      fullPath: '/imprenta'
      preLoaderRoute: typeof ImprentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impresion-textil': {
      id: '/impresion-textil'
      path: '/impresion-textil'
      fullPath: '/impresion-textil'
      preLoaderRoute: typeof ImpresionTextilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitaciones-de-boda': {
      id: '/invitaciones-de-boda'
      path: '/invitaciones-de-boda'
      fullPath: '/invitaciones-de-boda'
      preLoaderRoute: typeof InvitacionesDeBodaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandising': {
      id: '/merchandising'
      path: '/merchandising'
      fullPath: '/merchandising'
      preLoaderRoute: typeof MerchandisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naturhouse': {
      id: '/naturhouse'
      path: '/naturhouse'
      fullPath: '/naturhouse'
      preLoaderRoute: typeof NaturhouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regalos-personalizados': {
      id: '/regalos-personalizados'
      path: '/regalos-personalizados'
      fullPath: '/regalos-personalizados'
      preLoaderRoute: typeof RegalosPersonalizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cuenta/': {
      id: '/_authenticated/cuenta/'
      path: '/'
      fullPath: '/cuenta/'
      preLoaderRoute: typeof AuthenticatedCuentaIndexRouteImport
      parentRoute: typeof AuthenticatedCuentaRoute
    }
    '/_authenticated/cuenta/descargas': {
      id: '/_authenticated/cuenta/descargas'
      path: '/descargas'
      fullPath: '/cuenta/descargas'
      preLoaderRoute: typeof AuthenticatedCuentaDescargasRouteImport
      parentRoute: typeof AuthenticatedCuentaRoute
    }
    '/_authenticated/cuenta/detalles': {
      id: '/_authenticated/cuenta/detalles'
      path: '/detalles'
      fullPath: '/cuenta/detalles'
      preLoaderRoute: typeof AuthenticatedCuentaDetallesRouteImport
      parentRoute: typeof AuthenticatedCuentaRoute
    }
    '/_authenticated/cuenta/direcciones': {
      id: '/_authenticated/cuenta/direcciones'
      path: '/direcciones'
      fullPath: '/cuenta/direcciones'
      preLoaderRoute: typeof AuthenticatedCuentaDireccionesRouteImport
      parentRoute: typeof AuthenticatedCuentaRoute
    }
    '/_authenticated/cuenta/pedidos': {
      id: '/_authenticated/cuenta/pedidos'
      path: '/pedidos'
      fullPath: '/cuenta/pedidos'
      preLoaderRoute: typeof AuthenticatedCuentaPedidosRouteImport
      parentRoute: typeof AuthenticatedCuentaRoute
    }
  }
}

interface AuthenticatedCuentaRouteChildren {
  AuthenticatedCuentaDescargasRoute: typeof AuthenticatedCuentaDescargasRoute
  AuthenticatedCuentaDetallesRoute: typeof AuthenticatedCuentaDetallesRoute
  AuthenticatedCuentaDireccionesRoute: typeof AuthenticatedCuentaDireccionesRoute
  AuthenticatedCuentaPedidosRoute: typeof AuthenticatedCuentaPedidosRoute
  AuthenticatedCuentaIndexRoute: typeof AuthenticatedCuentaIndexRoute
}

const AuthenticatedCuentaRouteChildren: AuthenticatedCuentaRouteChildren = {
  AuthenticatedCuentaDescargasRoute: AuthenticatedCuentaDescargasRoute,
  AuthenticatedCuentaDetallesRoute: AuthenticatedCuentaDetallesRoute,
  AuthenticatedCuentaDireccionesRoute: AuthenticatedCuentaDireccionesRoute,
  AuthenticatedCuentaPedidosRoute: AuthenticatedCuentaPedidosRoute,
  AuthenticatedCuentaIndexRoute: AuthenticatedCuentaIndexRoute,
}

const AuthenticatedCuentaRouteWithChildren =
  AuthenticatedCuentaRoute._addFileChildren(AuthenticatedCuentaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCuentaRoute: AuthenticatedCuentaRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  CondicionesDeVentaRoute: CondicionesDeVentaRoute,
  ContactoRoute: ContactoRoute,
  DisenoGraficoRoute: DisenoGraficoRoute,
  EmpresaRoute: EmpresaRoute,
  EventosPersonalizadosRoute: EventosPersonalizadosRoute,
  GranFormatoRoute: GranFormatoRoute,
  ImprentaRoute: ImprentaRoute,
  ImpresionTextilRoute: ImpresionTextilRoute,
  InvitacionesDeBodaRoute: InvitacionesDeBodaRoute,
  McpRoute: McpRoute,
  MerchandisingRoute: MerchandisingRoute,
  NaturhouseRoute: NaturhouseRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  RegalosPersonalizadosRoute: RegalosPersonalizadosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
